<?php
// view all item ...
$app->get('/api/v1/store-config-stock/view' ,'StoreConfigStockController:viewStoreConfigStock');

// update the store config info ...
$app->put('/api/v1/store-config-stock/update' ,'StoreConfigStockController:updateStoreConfigStock');
