<?php
// view all item ...
$app->get('/api/v1/store-config-message/view' ,'StoreConfigMessageController:viewStoreConfigMessage');

// update the store config info ...
$app->put('/api/v1/store-config-message/update' ,'StoreConfigMessageController:updateStoreConfigMessage');
